### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by omkarsunku** [crypticcoinvip/CrypticCoin#1]
Hello,

### Describe the issue
Please provide a general summary of the issue you're experiencing
I started the crypticcoind my internet connection is fine but I am getting an error described. Help me out how can I solve this error/warning.

### Expected behaviour
I running this node on ubuntu 16.04LTS

crypticcoin-cli getinfo
{
  "version": 1010250,
  "protocolversion": 170005,
  "walletversion": 60000,
  "balance": {
    "transparent": 0.00000000,
    "coinbase": 0.00000000,
    "private": 0.00000000,
    "total": 0.00000000
  },
  "blocks": 32246,
  "timeoffset": -3,
  "connections": 8,
  "proxy": "",
  "difficulty": 10383.88488888593,
  "testnet": false,
  "keypoololdest": 1539455515,
  "keypoolsize": 102,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": "WARNING: check your network connection, 33 blocks received in the last 4 hours (96 expected)"
}

### The version of Crypticcoin you were using:
Run `crypticcoind --version` 
Crypticcoin Daemon version v1.1.2-9b3d578

I tried restarting the node the several times but the error/warning still appears and my connection is working fine. Please help me out how can I solve this warning "check your network connection, 33 blocks received in the last 4 hours (96 expected)"

Thanks,
Omkar

**Comment by crypticcoinvip** [comment]
At the time of the issue submitting, actual hashrate was lower than the difficulty
